name: Create release

on:
  push:
    branches: master
    tags:
    - 'v*'

  workflow_run:
    workflows: Tests
    branches: master
    types:
    - completed

env:
  BUILD_TYPE: Release
  CC: x86_64-w64-mingw32-gcc

jobs:
  on-success:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up MinGW
      uses: egor-tensin/setup-mingw@v2
      with:
        platform: x64

    - name: Configure CMake
      run: cmake -B ${{github.workspace}} -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}} --config ${{env.BUILD_TYPE}}

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        draft: true
        files: ${{github.workspace}}/bin/pei.exe
